### ISSUE TITLE
ERROR Unsupported binding does not tell which binding is affected

### ISSUE THREAD

**Issue by rhoerbe** [rohe/saml2test#1]
I received following message from a test:
saml2c.py -J testshibPvAt.json -c idp_test_config 'authn'
{"status": 4, "tests": [{"status": 1, "id": "check-saml2int-metadata", "name": "Checks that the Metadata follows the Saml2Int profile"}, {"status": 4, "message": "Unsupported binding", "id": "check", "name": "Verifies that the IdP supports the needed functionality"}, {"status": 4, "content": "Traceback (most recent call last):\n  File \"/usr/lib/python2.6/site-packages/saml2test-0.4.1-py2.6.egg/idp_test/**init**.py\", line 262, in run\n    conv.do_sequence(oper)\n  File \"/usr/lib/python2.6/site-packages/saml2test-0.4.1-py2.6.egg/srtest/tool.py\", line 257, in do_sequence\n    self.init(phase)\n  File \"/usr/lib/python2.6/site-packages/saml2test-0.4.1-py2.6.egg/idp_test/base.py\", line 166, in init\n    self.test_sequence(self.oper.tests[\"pre\"])\n  File \"/usr/lib/python2.6/site-packages/saml2test-0.4.1-py2.6.egg/srtest/tool.py\", line 89, in test_sequence\n    self.do_check(test, **kwargs)\n  File \"/usr/lib/python2.6/site-packages/saml2test-0.4.1-py2.6.egg/srtest/tool.py\", line 71, in do_check\n    self.check_severity(stat)\n  File \"/usr/lib/python2.6/site-packages/saml2test-0.4.1-py2.6.egg/srtest/tool.py\", line 63, in check_severity\n    raise FatalError\nFatalError\n", "message": "Exception: "}], "id": "authn"}
0.032201 [ERROR] WHERE: check
0.032247 [ERROR] STATUS:CRITICAL
0.032259 [ERROR] INFO: Unsupported binding

The response does not tell which binding is unsupported, and for which side: A binding requested by the SP is not supported by the IDP, or the other way round?

**Comment by rohe** [comment]
Fixed in the last check in.

**Comment by rhoerbe** [comment]
Thanks, now it reports:

0.016474 [ERROR] INFO: Unsupported binding at the IdP: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect

And this is correct, because saml2int requires HTTP-Redirect. Id removed that temporarily from the IdP to do test with a STORK IdP and forgot to restore.

Am 06.07.2013 um 09:04 schrieb Roland Hedberg notifications@github.com:
