### ISSUE TITLE
saml2c.py -C option

### ISSUE THREAD

**Issue by rhoerbe** [rohe/saml2test#10]
The documentation of -C says:
      -C CA_CERTS          CA certs to use to verify HTTPS server certificates, if
                           HTTPS is used and no server CA certs are defined then
                           no cert verification will be done

However, if -C is not given, the "bad certificate" message still appears. Also, it would be a fail-safe default to complain if the parameter is left out, like curl does it with the --insecure option.

**Comment by rohe** [comment]
19 jul 2013 kl. 11:18 skrev Rainer Hörbe notifications@github.com:

> The documentation of -C says:
> -C CA_CERTS CA certs to use to verify HTTPS server certificates, if
> HTTPS is used and no server CA certs are defined then
> no cert verification will be done
> 
> However, if -C is not given, the "bad certificate" message still appears.

Sorry, can't reproduce this !

> Also, it would be a fail-safe default to complain if the parameter is left out, like curl does it with the --insecure option.

That would be a good idea.

-- Roland
"Education is the path from cocky ignorance to miserable uncertainty.” - Mark Twain

**Comment by rhoerbe** [comment]
Resolved, does work with proper ca-bundle. Problem was that intermediate CA cert was missing. Using the mozilla ca_bundle.crt did the job.
