### ISSUE TITLE
Metadata as specified for pySAML2 "Configuration of pySAML2 entities"

### ISSUE THREAD

**Issue by rhoerbe** [rohe/saml2test#11]
The "How to sue" page for SAML2test describes the configuration for the test driver'S entity as "a normal PySAML2 configuration file." Hence it should be possible to use those options as described in the pysaml2 doc.

However, if the metadata entry contains a file name or url it does not work. The resulting JSON does not contain the metadata contents, but just the file name or url. A following run of saml2c.py will fail.

Alternatives to fix: document the difference to pysaml2, or add described functionality.

**Comment by rohe** [comment]
19 jul 2013 kl. 21:40 skrev Rainer Hörbe notifications@github.com:

> The "How to sue" page for SAML2test describes the configuration for the test driver'S entity as "a normal PySAML2 configuration file." Hence it should be possible to use those options as described in the pysaml2 doc.
> 
> However, if the metadata entry contains a file name or url it does not work. The resulting JSON does not contain the metadata contents, but just the file name or url. A following run of saml2c.py will fail.

Please supply me with an example.

-- Roland
"Education is the path from cocky ignorance to miserable uncertainty.” - Mark Twain

**Comment by rohe** [comment]
OK, now I get it. I think I misunderstood what you where referring to. 
So instead of the present simple syntax:

metadata = <string>  # which is what is there now or the pysaml2 version

you want to use the pySAML2 configuration syntax.

Right, I can see some reasons for that. Will change.
