### ISSUE TITLE
saml2c.py operation optional/option to execute all operations

### ISSUE THREAD

**Issue by rhoerbe** [rohe/saml2test#12]
a) The operation is specified as optional, but a missing operation causes a "Missing test case specification" Exception.

b) For the use case where operations are generated from the repository it would be good to execute all available operations in the file specified by -O. 

Suggestion: Make the oper argument mandatory except when a new option -o is given, that will execute all available operations.

**Comment by rohe** [comment]
22 jul 2013 kl. 08:12 skrev Rainer Hörbe notifications@github.com:

> a) The operation is specified as optional, but a missing operation causes a "Missing test case specification" Exception.
> 
> oper has to be optional since it has no meaning if you use either of the options -l or -m.
> 
> b) For the use case where operations are generated from the repository it would be good to execute all available operations in the file specified by -O.
> 
> Suggestion: Make the oper argument mandatory except when a new option -o is given, that will execute all available operations.

saml2c.py/saml2i.py are designed to only run one test and they will remain that way.
If you want to run a sequence of tests then we have to produce a script that does that and internally uses for instance saml2c.py.
I actually have such a script though it is not presently part of the distribution.

-- Roland
"Education is the path from cocky ignorance to miserable uncertainty.” - Mark Twain

**Comment by rhoerbe** [comment]
Am 30.07.2013 um 10:24 schrieb Roland Hedberg notifications@github.com:

> 22 jul 2013 kl. 08:12 skrev Rainer Hörbe notifications@github.com: 
> 
> > a) The operation is specified as optional, but a missing operation causes a "Missing test case specification" Exception. 
> > 
> > oper has to be optional since it has no meaning if you use either of the options -l or -m. 

OK.

> > b) For the use case where operations are generated from the repository it would be good to execute all available operations in the file specified by -O. 
> > 
> > Suggestion: Make the oper argument mandatory except when a new option -o is given, that will execute all available operations. 
> 
> saml2c.py/saml2i.py are designed to only run one test and they will remain that way. 
> If you want to run a sequence of tests then we have to produce a script that does that and internally uses for instance saml2c.py. 
> I actually have such a script though it is not presently part of the distribution. 

To simplify the interface between repository, backend and GUI the backend should be able to execute all available tests. If this is done with another script than saml2c.py that is fine as well.

Regards, Rainer

**Comment by rohe** [comment]
Having the script only do one test at the time was chosen to allow the user through the GUI to chose which tests to run. So in the basic setup the GUI handles what constitutes 'all available tests'. In the case there is no GUI involved I've added a script that runs all tests one-by-one.
