### ISSUE TITLE
CheckSaml2IntMetaData does not complain about expired Metadata

### ISSUE THREAD

**Issue by rhoerbe** [rohe/saml2test#14]
Testing the authn operation with stale MD does not result in a warning:

<md:EntitiesDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata"  validUntil="2013-08-19T23:59:59Z" 

The operation has CheckSaml2IntMetaData configured as "pre" check.

**Comment by rohe** [comment]
Fixed
