### ISSUE TITLE
No handlers could be found for logger "srtest.tool"

### ISSUE THREAD

**Issue by rhoerbe** [rohe/saml2test#5]
starting "saml2c.py -J testshibPvAt.json -c idp_test_config 'authn'", the first message complains about the missing srtest.tool logger. The only logger defined in the tool's SP is: 

```
"logger": {
    "rotating": {
        "filename": "sp.log",
        "maxBytes": 100000,
        "backupCount": 5,
        },
    "loglevel": "info",
    }
```

How to define this logger? Which attribute is the ID of the logger?

**Comment by rohe** [comment]
The problem has nothing to do with the logger definition in the configuration file.
The problem was that there was no srtest logger defined.
Such a definition is added now so this should not be a problem anymore.
